<?xml version='1.0'?>

<robot name="titan" xmlns:xacro="http://www.ros.org/wiki/xacro">
	<xacro:property name="M_PI" value="3.14159"/>
	<xacro:property name="rotate90CCW" value="${3.14159 / 2}"/>
	<xacro:property name="rotate90CW" value="${-3.14159 / 2}"/>

	<xacro:property name="total_mass" value="15"/>
	
	<xacro:property name="plate_x" value="0.2286"/>
	<xacro:property name="plate_y" value="0.3048"/>
	<xacro:property name="plate_z" value="0.002286"/>
	<xacro:property name="plate_offset" value="0.0508"/>
	<xacro:property name="plate_mass" value="0.317515"/>

	<xacro:property name="base_x_size" value="${plate_x*2}"/>
	<xacro:property name="base_y_size" value="${plate_y}"/>
	<xacro:property name="base_z_size" value="0.075"/>
	<xacro:property name="base_mass" value="${plate_mass*2}"/>

	<xacro:property name="laser_x_size" value="0.125"/>
	<xacro:property name="laser_y_size" value="0.105"/>
	<xacro:property name="laser_z_size" value="0.07"/>
	<xacro:property name="laser_mass" value="0.05"/>

	<xacro:property name="long_channel_x" value="0.4572"/>
	<xacro:property name="long_channel_y" value="0.0381"/>
	<xacro:property name="long_channel_z" value="0.002286"/>
	<xacro:property name="long_channel_mass" value="0.1950447"/>

	<xacro:property name="short_channel_x" value="0.4572"/>
	<xacro:property name="short_channel_y" value="0.0381"/>
	<xacro:property name="short_channel_mass" value="0.0952544"/>

	<xacro:property name="wheelbase" value="0.345" />
	<xacro:property name="track" value="0.355" />

	<xacro:property name="wheel_vertical_offset" value="0.0762" />

	<xacro:property name="wheel_radius" value="0.0762" />
	<xacro:property name="wheel_length" value="0.025" />

	<xacro:property name="camera_link" value="0.05" />

	<xacro:arg name="robot_namespace" default="/" />
	
	<xacro:include filename="$(find titan_description)/urdf/materials.xacro" />
	<xacro:include filename="$(find titan_description)/urdf/macros.xacro" />
	<xacro:include filename="$(find titan_description)/urdf/wheel.xacro" />
	<xacro:include filename="$(find titan_description)/urdf/titan.gazebo" />

	

	<link name="base_link">
		<pose xyz="0 0 1" rpy="0 0 0" />
		<!-- <inertial>
			<mass value="${total_mass}" />
			<origin xyz="0 0 ${(base_z_size/2) + plate_offset}" rpy=" 0 0 0"/>
			<xacro:box_inertia m="${total_mass}" x="${base_x_size}" y="${base_y_size}" z="${base_z_size}" />
		</inertial> -->

		

		<collision name='collision'>
			<origin xyz="0 0 ${(base_z_size/2) + plate_offset}" rpy="0 0 0" />
			<geometry>
				<box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
			</geometry>
		</collision>

		<visual name='base_solid'>
			<origin xyz="0 0 ${(base_z_size/2) + plate_offset}" rpy="0 0 0" />
			<geometry>
				<box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
			</geometry>
			<material name="white"/>
		</visual>
		
		
	</link>

	<link name="inertia_link">
		<inertial>
			<mass value="${total_mass}" />
			<origin xyz="0 0 ${(base_z_size/2) + plate_offset}" rpy=" 0 0 0"/>
			<xacro:box_inertia m="${total_mass}" x="${base_x_size}" y="${base_y_size}" z="${base_z_size}" />
		</inertial> 
	</link>

	<link name="laserbox_link">
		<visual name='laser_box'>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="${laser_x_size} ${laser_y_size} ${laser_z_size}"/>
			</geometry>
			<material name="black"/>
		</visual>
	</link>

	<link name="laser">
		<visual name='laser'>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<cylinder length="0.01" radius="0.04"/>
			</geometry>
			<material name="red"/>
		</visual>
	</link>

	<link name="imu_link">	
		<visual name='imu_box'>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="0.02 0.02 0.02"/>
			</geometry>
			<material name="green"/>
		</visual>
	</link>

	<link name="camera_link">
                <visual name='camera_box'>
                        <origin xyz="0 0 0" rpy="0 0 0"/>
                        <geometry>
                                <box size="0.05 0.05 0.05"/>
                        </geometry>
                        <material name="green"/>
                </visual>
        </link>


	<joint name="base_to_inertia" type="fixed">
		<parent link="base_link"/>
		<child link="inertia_link"/>
		<origin xyz="0 0 0"/>
	</joint>

	<joint name="base_to_camera" type="fixed">
                <parent link="base_link"/>   
                <child link="camera_link"/> 
                <origin xyz="0.2 0 ${(base_z_size/2) + plate_offset + 0.05}" rpy="0 0 0" />
        </joint>


	<joint name="base_to_laserbox" type="fixed">
		<parent link="base_link"/>
		<child link="laserbox_link"/>
		<origin xyz="0.025 0.08 ${(base_z_size/2) + plate_offset + laser_z_size}" rpy="0 0 0" />
	</joint>

	<joint name="laserbox_to_laser" type="fixed">
		<parent link="laserbox_link"/>
		<child link="laser"/>
		<origin xyz="0 0 ${(laser_z_size/2)+ (0.01/2)}"/>
	</joint>

	<joint name="base_to_imu_link" type="fixed">
		<parent link="base_link"/>
		<child link="imu_link"/>
		<origin xyz="-0.050 -0.010 ${(base_z_size/2) + plate_offset + 0.02}" rpy="0 0 ${0}"/>
	</joint>

	

	<xacro:titan_wheel wheel_prefix="front_left">
		<origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
	</xacro:titan_wheel>
	<xacro:titan_wheel wheel_prefix="front_right">
		<origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
	</xacro:titan_wheel>
	<xacro:titan_wheel wheel_prefix="rear_left">
		<origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
	</xacro:titan_wheel>
	<xacro:titan_wheel wheel_prefix="rear_right">
	<origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
	</xacro:titan_wheel>

	<gazebo>
		<plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
			<robotNamespace>$(arg robot_namespace)</robotNamespace>
		</plugin>
	</gazebo>

	<gazebo>
		<plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
			<updateRate>100.0</updateRate>
			<robotNamespace>/</robotNamespace>
			<leftFrontJoint>front_left_wheel</leftFrontJoint>
			<rightFrontJoint>front_right_wheel</rightFrontJoint>
			<leftRearJoint>rear_left_wheel</leftRearJoint>
			<rightRearJoint>rear_right_wheel</rightRearJoint>
			<wheelSeparation>0.36</wheelSeparation>
			<wheelDiameter>0.101</wheelDiameter>
			<robotBaseFrame>base_link</robotBaseFrame>
			<torque>20</torque>
			<commandTopic>cmd_vel</commandTopic>
			<odometryFrame>odom</odometryFrame>
			<odometryTopic>odom</odometryTopic>
			<broadcastTF>false</broadcastTF>
		</plugin>
	</gazebo>
	

	
</robot>

