<?xml version='1.0'?>

<robot name="titan" xmlns:xacro="http://ros.org/wiki/xacro">
	<xacro:property name="M_PI" value="3.14159"/>
	<xacro:property name="rotate90CCW" value="${3.14159 / 2}"/>
	<xacro:property name="rotate90CW" value="${-3.14159 / 2}"/>

	<xacro:property name="total_mass" value="15"/>
	
	<xacro:property name="base_x_size" value="0.7556"/>
	<xacro:property name="base_y_size" value="0.4572"/>
	<xacro:property name="base_z_size" value="0.0508"/>
	<xacro:property name="base_mass" value="10"/>

	<xacro:property name="laser_x_size" value="0.125"/>
	<xacro:property name="laser_y_size" value="0.105"/>
	<xacro:property name="laser_z_size" value="0.07"/>
	<xacro:property name="laser_mass" value="0.05"/>

	<xacro:property name="wheelbase" value="0.58" />
	<xacro:property name="track" value="0.25" />

	<xacro:property name="wheel_vertical_offset" value="0.0" />

	<xacro:property name="wheel_radius" value="0.09" />
	<xacro:property name="wheel_length" value="0.0508" />

	<xacro:property name="camera_link" value="0.05" />

	<xacro:arg name="robot_namespace" default="/" />
	
	<xacro:include filename="$(find titan_description)/urdf/materials.xacro" />
	<xacro:include filename="$(find titan_description)/urdf/macros.xacro" />
	<xacro:include filename="$(find titan_description)/urdf/wheel.xacro" />
	<xacro:include filename="$(find titan_description)/urdf/titan.gazebo" />
	<xacro:include filename="$(find titan_description)/urdf/sick_tim.urdf.xacro" />
	

	<link name="base_link">
		<pose xyz="0 0 0" rpy="0 0 0" />

		<collision name='collision'>
			<origin xyz="0 0 ${-(base_z_size/2)}" rpy="0 0 0" />
			<geometry>
				<box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
			</geometry>
		</collision>

		<visual name='base_solid'>
			<origin xyz="0 0 ${-(base_z_size/2)}" rpy="0 0 0" />
			<geometry>
				<box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
			</geometry>
			<material name="white"/>
		</visual>
	</link>

	<link name="inertia_link">
		<inertial>
			<mass value="${total_mass}" />
			<origin xyz="0 0 0" rpy=" 0 0 0"/>
			<xacro:box_inertia m="${total_mass}" x="${base_x_size}" y="${base_y_size}" z="${base_z_size}" />
		</inertial> 
	</link>

	<xacro:sick_tim551 name="laser" ros_topic="scan" />

	<link name="imu_link">	
		<visual name='imu_box'>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="0.02 0.02 0.02"/>
			</geometry>
			<material name="green"/>
		</visual>
		<!-- <inertial>
                        <mass value="${0.005}" />
                        <origin xyz="0 0 0" rpy=" 0 0 0"/>
                        <xacro:box_inertia m="${0.005}" x="${0.05}" y="${0.05}" z="${0.05}" />
                </inertial> -->
	</link>

	<gazebo reference="imu_link">
  	</gazebo>

	<link name="camera_link">
                <visual name='camera_box'>
                        <origin xyz="0 0 0" rpy="0 0 0"/>
                        <geometry>
                                <box size="0.05 0.05 0.05"/>
                        </geometry>
                        <material name="green"/>
                </visual>
		<!-- <inertial>
                        <mass value="${0.05}" />
                        <origin xyz="0 0 0" rpy=" 0 0 0"/>
                        <xacro:box_inertia m="${0.005}" x="${0.05}" y="${0.05}" z="${0.05}" />
                </inertial> -->

        </link>


	<joint name="base_to_inertia" type="fixed">
		<parent link="base_link"/>
		<child link="inertia_link"/>
		<origin xyz="0 0 0"/>
	</joint>

	<joint name="base_to_camera" type="fixed">
                <parent link="base_link"/>   
                <child link="camera_link"/> 
                <origin xyz="0.13 0.08 ${(base_z_size/2) + 0.3}" rpy="0 0 0" />
        </joint>


	<joint name="base_to_laser" type="fixed">
		<parent link="base_link"/>
		<child link="laser_mount_link"/>
		<origin xyz="0.31 0.0 0.08" rpy="0 0 0" />
	</joint>


	<joint name="base_to_imu_link" type="fixed">
		<parent link="base_link"/>
		<child link="imu_link"/>
		<origin xyz="0 0 ${(base_z_size/2)  + 0.02}" rpy="0 0 0"/>
	</joint>

	

	<xacro:titan_wheel wheel_prefix="left_front">
		<origin xyz="${track} ${wheelbase/2} ${wheel_vertical_offset}" rpy="0 0 0" />
	</xacro:titan_wheel>

	<xacro:titan_wheel wheel_prefix="left_mid">
                <origin xyz="0 ${wheelbase/2} ${wheel_vertical_offset}" rpy="0 0 0" />
        </xacro:titan_wheel>

	<xacro:titan_wheel wheel_prefix="left_rear">
		<origin xyz="${-track} ${wheelbase/2} ${wheel_vertical_offset}" rpy="0 0 0" />
	</xacro:titan_wheel>


	<xacro:titan_wheel wheel_prefix="right_front">
		<origin xyz="${track} ${-wheelbase/2} ${wheel_vertical_offset}" rpy="0 0 0" />
	</xacro:titan_wheel>

	<xacro:titan_wheel wheel_prefix="right_mid">
                <origin xyz="0 ${-wheelbase/2} ${wheel_vertical_offset}" rpy="0 0 0" />
        </xacro:titan_wheel>

	<xacro:titan_wheel wheel_prefix="right_rear">
		<origin xyz="${-track} ${-wheelbase/2} ${wheel_vertical_offset}" rpy="0 0 0" />
	</xacro:titan_wheel>

	<gazebo>
		<plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
			<robotNamespace>$(arg robot_namespace)</robotNamespace>
		</plugin>
	</gazebo>

	<!--<gazebo>
		<plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
			<updateRate>100.0</updateRate>
			<robotNamespace>/</robotNamespace>
			<leftFrontJoint>front_left_wheel</leftFrontJoint>
			<rightFrontJoint>front_right_wheel</rightFrontJoint>
			<leftRearJoint>rear_left_wheel</leftRearJoint>
			<rightRearJoint>rear_right_wheel</rightRearJoint>
			<wheelSeparation>0.36</wheelSeparation>
			<wheelDiameter>0.101</wheelDiameter>
			<robotBaseFrame>base_link</robotBaseFrame>
			<torque>20</torque>
			<commandTopic>cmd_vel</commandTopic>
			<odometryFrame>odom</odometryFrame>
			<odometryTopic>odom</odometryTopic>
			<broadcastTF>false</broadcastTF>
		</plugin>
	</gazebo> -->

	<gazebo>
		<plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
		<robotNamespace>$(arg robot_namespace)</robotNamespace>

		<alwaysOn>true</alwaysOn>
		<updateRate>100</updateRate>
		<leftJoint>left_mid_wheel</leftJoint>
		<rightJoint>right_mid_wheel</rightJoint>
		<wheelSeparation>0.68</wheelSeparation>
		<wheelDiameter>0.18</wheelDiameter>
		<torque>20</torque>
		<commandTopic>/cmd_vel</commandTopic>
		<odometryTopic>/odom</odometryTopic>
		<odometryFrame>map</odometryFrame>
		<robotBaseFrame>base_link</robotBaseFrame>

		<legacyMode>false</legacyMode>

		<rosDebugLevel>Debug</rosDebugLevel>
		<publishWheelTF>true</publishWheelTF>
		<publishWheelJointState>true</publishWheelJointState>
		<wheelAcceleration>5</wheelAcceleration>
		<wheelTorque>20</wheelTorque>
		<publishTf>1</publishTf>
		<odometrySource>encoder</odometrySource>
		</plugin>
	</gazebo>


	<gazebo>
		<plugin name="imu_controller" filename="libhector_gazebo_ros_imu.so">
			<robotNamespace>$(arg robot_namespace)</robotNamespace>
			<updateRate>50.0</updateRate>
			<bodyName>base_link</bodyName>
			<topicName>imu/data</topicName>
			<accelDrift>0.005 0.005 0.005</accelDrift>
			<accelGaussianNoise>0.005 0.005 0.005</accelGaussianNoise>
			<rateDrift>0.005 0.005 0.005 </rateDrift>
			<rateGaussianNoise>0.005 0.005 0.005 </rateGaussianNoise>
			<headingDrift>0.005</headingDrift>
			<headingGaussianNoise>0.005</headingGaussianNoise>
		</plugin>
	</gazebo>
	

	
</robot>

