titan_joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

titan_arm_controller2:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - base_to_zaxis
    - link1_to_link2
    - link2_to_link3
