controller_list:
  - name: titan_arm_controller
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [base_to_zaxis, link1_to_link2, link2_to_link3, link3_to_eef]
#  - name: titan_eef_controller
#    action_ns: joint_trajectory_action
#    type: FollowJointTrajectory
#    joints: [link3_to_eef]

