controller_list:
  - name: fake_EEFGroup_controller
    joints:
      - link3_to_eef
  - name: fake_ArmGroup_controller
    joints:
      - base_to_zaxis
      - link1_to_link2
      - link2_to_link3
      - link3_to_eef