sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /camera/depth_registered/points
    max_range: 5.0
    point_subsample: 1
    padding_offset: 0.05
    padding_scale: 0.8
    shape_padding: 0.01
    shape_scale: 1.0
    filtered_cloud_topic: filtered_cloud
    self_mask:
      min_sensor_dist: 0.8
      self_see_default_padding: 0.04
      self_see_default_sacle: 1.0
